#!/bin/bash

echo "Receive a basic message"
./climsg
echo "And again"
./climsg
echo "Receive a type 56 (for instance) message"
./climsg -t 56
echo "Set the key and receive message"
./climsg -k 12345
echo "Delete message queue"
./climsg -d
